### ISSUE TITLE
Export: HE template font size massively increases when the title is too long

### ISSUE THREAD

**Issue by ValentinFutterer** [tuwien-csd/damap-backend#185] opened 2024-04-30 10:23 UTC
**Describe the bug**
When exporting a DMP to HE, the font size in the DMP gets set so high, that it takes up 500 pages. This is triggered by choosing a long title, e.g. `Exploring Recombination Rates in Fleckvieh and Braunvieh Cattle Breeds and their Correlation with SNP and GC Content Densities`.

**Is this a regression?**
Yes

**Steps to Reproduce**
Export a DMP to HE with the above mentioned title.

**Expected behavior**
The normal text font should not be adjusted.

**Environment**
 - Damap version 3.0.1

**Comment by rekt-hard** [comment] 2024-05-06 12:13
Just tested it with version 3.0.2 (current). Could not reproduce this behaviour locally with the provided project title.
Maybe this was fixed in-between?

**Closed as completed** 2024-05-06 13:55 UTC
Labels: bug
