### ISSUE TITLE
Sometimes dataset list in storage section will have reversed sequence.

### ISSUE THREAD

**Issue by ZenoLC** [tuwien-csd/damap-backend#104] opened 2023-07-12 09:07 UTC
**Describe the bug**
When exporting a document the datasets listed in the storage section 3a will sometimes have a reversed sequence (i.e. P* IDs go from highest to lowest).

**Is this a regression?**
No.

**Steps to Reproduce**
Currently unknown how to reproduce.

**Expected behavior**
The P* IDs of the datasets should always be in ascending sequence.

**Example**
"P3 (Marekting materials), P1 (Survey whith Horizon Projects) will be stored in..."

**Environment**
 - Damap version 2.4.0

**Comment by rekt-hard** [comment] 2024-03-26 12:40
could not reproduce. Closing it for now. Can be reopened if such issues surface again.

**Closed by rekt-hard** 2024-03-26 12:40 UTC
Labels: bug
